name: WebServicesAssignment1
values:
  - key: baseUrl
    value: 'http://127.0.0.1:8000'
    enabled: true
  - key: testProductName
    value: TestProduct
    enabled: true
  - key: testProductUnitPrice
    value: '9.99'
    enabled: true
  - key: testProductStockQuantity
    value: '50'
    enabled: true
  - key: testProductDescription
    value: A test product created by Postman automation
    enabled: true
color: 60
